// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import MiniDrawer from "./Sidebar/page";

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
      
// //       <body className={inter.className}>
// //         <MiniDrawer>{children}</MiniDrawer>

// //   </body>
// //     </html>
// //   );
// // }


// 'use client'

// import { Inter } from "next/font/google";
// import "./globals.css";
// import MiniDrawer from "./Sidebar/page";
// import { useRouter } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   const { pathname } = useRouter(); // Get the current path

//   // Conditionally render MiniDrawer based on the path
//   const showSidebar = pathname !== '/login';

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {showSidebar ? <MiniDrawer>{children}</MiniDrawer> : children}
//       </body>
//     </html>
//   );
// }


"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import MiniDrawer from "./Sidebar/page";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const { pathname } = router;

  // Only show MiniDrawer if the current path is not `/login`
  const showSidebar = pathname !== '/login';

  return (
    <html lang="en">
      <body className={inter.className}>
        {showSidebar ? <MiniDrawer>{children}</MiniDrawer> : children}
      </body>
    </html>
  );
}
